apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    appstudio.openshift.io/application: integ-app-mcur
    appstudio.openshift.io/component: integration-suite-test-component-git-source-ecvh
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: integration-suite-test-component-git-source-ecvh
  namespace: integration-e2e-mwcu
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: integration-suite-test-component-git-source-ecvh
status:
  configuration:
    generatedName: ""
